project_id = "qpclydixqgzjxnllargu"

[functions.registrar-uso-cupom]
verify_jwt = false

[functions.calcular-distancia]
verify_jwt = false

[functions.ga4-analytics]
verify_jwt = false

[functions.update-cron]
verify_jwt = false

[functions.calcular-frete-superfrete]
verify_jwt = false

[functions.criar-stripe-checkout]
verify_jwt = false

[functions.verificar-stripe-pagamento]
verify_jwt = false
