

-- 1
create table public.ceps_especiais (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  cep text null,
  valor numeric null,
  constraint ceps_especiais_pkey primary key (id)
) TABLESPACE pg_default;
alter table "public"."ceps_especiais" enable row level security;
create policy "Acesso público total temporário"
on "public"."ceps_especiais"
as PERMISSIVE
for ALL -- Isso cobre todas as operações de uma vez
to public
using (true)       -- Permite visualizar/deletar/atualizar
with check (true); -- Permite inserir/atualizar novos dados

-- 2
create table public.cupons (
  id uuid not null default extensions.uuid_generate_v4 (),
  nome text not null,
  descricao text null,
  tipo text not null,
  valor numeric not null,
  data_inicio date not null,
  data_fim date not null,
  limite_uso integer null,
  usos_por_usuario integer null,
  valor_minimo_pedido numeric null,
  ativo boolean null default true,
  criado_em timestamp without time zone null,
  origem text null,
  usos numeric null default '0'::numeric,
  produtos_requeridos jsonb null,
  produto_brinde jsonb null,
  constraint cupons_pkey primary key (id),
  constraint cupons_nome_key unique (nome),
  constraint cupons_tipo_check check (
    (
      tipo = any (
        array[
          'percentual'::text,
          'fixo'::text,
		  'frete_gratis'::text,
          'compre_e_ganhe'::text
        ]
      )
    )
  )
) TABLESPACE pg_default;
-- RLS cupons
alter table "public"."cupons" enable row level security;
create policy "Acesso público total temporário"
on "public"."cupons"
as PERMISSIVE
for ALL
to public
using (true)
with check (true);


-- 3
-- Cria a função no schema public
CREATE OR REPLACE FUNCTION public.update_empresa_info_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;
create table public.empresa_info (
  id uuid not null default gen_random_uuid (),
  nome text not null,
  endereco text null,
  telefone text null,
  whatsapp text null,
  created_at timestamp with time zone null default now(),
  updated_at timestamp with time zone null default now(),
  cep text not null,
  rua text null,
  bairro text null,
  cidade text null,
  estado text null,
  complemento text null,
  pais text null,
  numero text null,
  modelo_frete text null default 'km_direto'::text,
  user_id uuid not null,
  constraint empresa_info_pkey primary key (id),
  constraint empresa_info_modelo_frete_check check (
    (
      modelo_frete = any (array['km_direto'::text, 'cep_distancia'::text])
    )
  )
) TABLESPACE pg_default;
alter table "public"."empresa_info" enable row level security;
create policy "Acesso público total temporário"
on "public"."empresa_info"
as PERMISSIVE
for ALL
to public
using (true)
with check (true);
create trigger update_empresa_info_timestamp BEFORE
update on empresa_info for EACH row
execute FUNCTION update_empresa_info_updated_at ();


-- 4
create table public.faixas_frete (
  id uuid not null default gen_random_uuid (),
  user_id uuid not null,
  km_inicial numeric not null,
  km_final numeric not null,
  valor numeric not null,
  created_at timestamp with time zone null default now(),
  constraint faixas_frete_pkey primary key (id),
  constraint km_inicial_menor_que_final check ((km_inicial < km_final))
) TABLESPACE pg_default;
alter table "public"."faixas_frete" enable row level security;
create policy "Acesso público total temporário"
on "public"."faixas_frete"
as PERMISSIVE
for ALL
to public
using (true)
with check (true);


-- 5
create table public.fidelidade_regras (
  id uuid not null default extensions.uuid_generate_v4 (),
  nome text not null,
  descricao text null,
  criterio text not null,
  meta numeric not null,
  premio_tipo text not null,
  premio_id uuid null,
  ativo boolean null default true,
  criado_em timestamp without time zone null default now(),
  constraint fidelidade_regras_pkey primary key (id),
  constraint fidelidade_regras_criterio_check check (
    (
      criterio = any (
        array['quantidade_compras'::text, 'valor_gasto'::text]
      )
    )
  ),
  constraint fidelidade_regras_premio_tipo_check check (
    (
      premio_tipo = any (array['cupom'::text, 'produto'::text])
    )
  )
) TABLESPACE pg_default;
alter table "public"."fidelidade_regras" enable row level security;
create policy "Acesso público total temporário"
on "public"."fidelidade_regras"
as PERMISSIVE
for ALL
to public
using (true)
with check (true);


-- 6
create table public.fidelidade_progresso (
  id uuid not null default gen_random_uuid (),
  telefone_cliente text not null,
  nome_cliente text null,
  contagem_pizzas integer not null default 0,
  valor_gasto_pizzas numeric not null default 0,
  ultima_atualizacao timestamp with time zone null default now(),
  criado_em timestamp with time zone null default now(),
  constraint fidelidade_progresso_pkey primary key (id),
  constraint fidelidade_progresso_telefone_cliente_key unique (telefone_cliente)
) TABLESPACE pg_default;
alter table "public"."fidelidade_progresso" enable row level security;
create policy "Acesso público total temporário"
on "public"."fidelidade_progresso"
as PERMISSIVE
for ALL
to public
using (true)
with check (true);


-- 7
create table public.usuarios (
  id uuid not null default gen_random_uuid (),
  user_id uuid not null,
  email text not null,
  whatsapp text null,
  empresa text null,
  created_at timestamp with time zone null default CURRENT_TIMESTAMP,
  role text null default 'cliente'::text,
  firebase_id text null,
  constraint usuarios_pkey primary key (id),
  constraint usuarios_firebase_id_key unique (firebase_id),
  constraint usuarios_user_id_unique unique (user_id),
  constraint usuarios_user_id_fkey foreign KEY (user_id) references auth.users (id) on delete CASCADE
) TABLESPACE pg_default;
alter table "public"."usuarios" enable row level security;
create policy "Acesso público total temporário"
on "public"."usuarios"
as PERMISSIVE
for ALL
to public
using (true)
with check (true);


-- 8
create table public.fidelidade_historico (
  id uuid not null default extensions.uuid_generate_v4 (),
  user_id uuid null,
  regra_id uuid null,
  data timestamp without time zone null default now(),
  premio_concedido boolean null default false,
  observacao text null,
  constraint fidelidade_historico_pkey primary key (id),
  constraint fidelidade_historico_regra_id_fkey foreign KEY (regra_id) references fidelidade_regras (id),
  constraint fidelidade_historico_user_id_fkey foreign KEY (user_id) references usuarios (id) on delete CASCADE
) TABLESPACE pg_default;
alter table "public"."fidelidade_historico" enable row level security;
create policy "Acesso público total temporário"
on "public"."fidelidade_historico"
as PERMISSIVE
for ALL
to public
using (true)
with check (true);


-- 9
create table public.pedidos_sabor_delivery (
  id uuid not null default gen_random_uuid (),
  codigo_pedido text null,
  status_atual text null,
  nome_cliente text null,
  telefone_cliente text null,
  endereco_entrega text null,
  observacoes text null,
  metodo_pagamento text null,
  valor_total numeric(10, 2) null,
  cupom_desconto text null,
  data_criacao timestamp with time zone null,
  horario_recebido timestamp with time zone null,
  motivo_cancelamento text null,
  atualizado_em timestamp with time zone null,
  origem text null,
  itens jsonb null,
  criado_em timestamp with time zone null default now(),
  atualizado_em_banco timestamp with time zone null default now(),
  codigo_curto text null,
  firebase_id text null,
  user_name text null,
  user_email text null,
  utm_source text null,
  utm_medium text null,
  utm_campaign text null,
  utm_content text null,
  utm_term text null,
  constraint pedidos_sabor_delivery_pkey primary key (id),
  constraint pedidos_sabor_delivery_codigo_curto_key unique (codigo_curto),
  constraint pedidos_sabor_delivery_codigo_pedido_key unique (codigo_pedido)
) TABLESPACE pg_default;
alter table "public"."pedidos_sabor_delivery" enable row level security;
create policy "Acesso público total temporário"
on "public"."pedidos_sabor_delivery"
as PERMISSIVE
for ALL
to public
using (true)
with check (true);


-- 10
create table public.users (
  created_at timestamp with time zone not null,
  email text null,
  last_sign_in_at timestamp with time zone null,
  name text null,
  phone text null,
  id uuid not null default gen_random_uuid (),
  firebase_id text null,
  user_id uuid null,
  role text null default 'user'::text,
  whatsapp_auth_code text null,
  first_utm_source text null,
  first_utm_campaign text null,
  constraint users_pkey primary key (id),
  constraint users_firebase_id_unique unique (firebase_id),
  constraint users_user_id_key unique (user_id),
  constraint users_user_id_fkey foreign KEY (user_id) references auth.users (id)
) TABLESPACE pg_default;
create index IF not exists idx_users_firebase_id on public.users using btree (firebase_id) TABLESPACE pg_default;

-- Cria RLS tabela users
alter table "public"."users" enable row level security;
create policy "Acesso público total temporário"
on "public"."users"
as PERMISSIVE
for ALL
to public
using (true)
with check (true);

-- 11
create table public.cupons_usos (
  id uuid not null default extensions.uuid_generate_v4 (),
  cupom_id uuid null,
  user_id uuid null,
  pedido_id uuid null,
  data_uso timestamp without time zone null default now(),
  constraint cupons_usos_pkey primary key (id),
  constraint cupons_usos_cupom_id_fkey foreign KEY (cupom_id) references cupons (id) on delete CASCADE,
  constraint cupons_usos_user_id_fkey foreign KEY (user_id) references users (id) on delete set null
) TABLESPACE pg_default;
create index IF not exists idx_cupons_usos_cupom_id on public.cupons_usos using btree (cupom_id) TABLESPACE pg_default;
create index IF not exists idx_cupons_usos_user_id on public.cupons_usos using btree (user_id) TABLESPACE pg_default;
create index IF not exists idx_cupons_usos_cupom_user on public.cupons_usos using btree (cupom_id, user_id) TABLESPACE pg_default;
alter table "public"."cupons_usos" enable row level security;
create policy "Acesso público total temporário"
on "public"."cupons_usos"
as PERMISSIVE
for ALL
to public
using (true)
with check (true);



-- 13
-- Cria a tabela para inserir as tags de rastreamento GTM, FB e CAPI FB
create table public.tags_rastreamento (
  id bigint not null default 1,
  meta_pixel_id text null,
  meta_access_token text null,
  meta_test_event_code text null,
  gtm_container_id text null,
  updated_at timestamp with time zone null default now(),
  capi_ativo boolean not null default false,
  constraint tags_rastreamento_pkey primary key (id)
) TABLESPACE pg_default;
-- Habilita RLS na tabela tags_rastreamento
alter table "public"."tags_rastreamento" enable row level security;
create policy "All Permissive"
on "public"."tags_rastreamento"
as PERMISSIVE
for ALL
to public
using (true)
with check (true);


-- 14
-- Cria a tabela onde serão salvas as credenciais firebase e supabase do projeto
create table public.configuracoes (
  id uuid not null default gen_random_uuid (),
  chave text not null,
  valor text null,
  created_at timestamp with time zone null default now(),
  updated_at timestamp with time zone null default now(),
  constraint configuracoes_pkey primary key (id),
  constraint configuracoes_chave_key unique (chave)
) TABLESPACE pg_default;
-- Habilita RLS na tabela configuracoes
alter table "public"."configuracoes" enable row level security;
create policy "All Permissive"
on "public"."configuracoes"
as PERMISSIVE
for ALL
to public
using (true)
with check (true);


-- 16
-- Cria a tabela de eventos dos produtos para métricas avancadas
-- Cria a RLS da tabela
-- Cria indices para consultas rapidas
-- Create product_events table
create table public.product_events (
  id uuid not null default gen_random_uuid (),
  product_id text not null,
  product_name text not null,
  event_type text not null,
  price numeric null default 0,
  category text null,
  quantity integer null default 1,
  session_id text null,
  created_at timestamp with time zone not null default now(),
  visitor_id text null,
  utm_source text null,
  utm_medium text null,
  utm_campaign text null,
  utm_content text null,
  utm_term text null,
  constraint product_events_pkey primary key (id)
) TABLESPACE pg_default;

create index IF not exists idx_product_events_product_id on public.product_events using btree (product_id) TABLESPACE pg_default;

create index IF not exists idx_product_events_event_type on public.product_events using btree (event_type) TABLESPACE pg_default;

create index IF not exists idx_product_events_created_at on public.product_events using btree (created_at) TABLESPACE pg_default;

create index IF not exists idx_product_events_product_event on public.product_events using btree (product_id, event_type) TABLESPACE pg_default;

create index IF not exists idx_product_events_visitor_session on public.product_events using btree (visitor_id, session_id, created_at) TABLESPACE pg_default;

create index IF not exists idx_product_events_event_type_created on public.product_events using btree (event_type, created_at) TABLESPACE pg_default;

-- Enable RLS
ALTER TABLE public.product_events ENABLE ROW LEVEL SECURITY;

-- Allow anonymous inserts (frontend tracking)
CREATE POLICY "Anyone can insert product events"
ON public.product_events
FOR INSERT
TO public
WITH CHECK (true);

-- Allow authenticated users to read (admin metrics)
CREATE POLICY "Authenticated users can read product events"
ON public.product_events
FOR SELECT
TO authenticated
USING (true);

-- Also allow anon to read for now (since the app uses anon key for admin)
CREATE POLICY "Anon can read product events"
ON public.product_events
FOR SELECT
TO anon
USING (true);



-- 17
-- Cria o bucket "imagens-cardapio" para salvar todas as imagens dos produtos com as RLS
-- Criar bucket público
insert into storage.buckets (id, name, public)
values ('imagens-cardapio', 'imagens-cardapio', true)
on conflict (id) do nothing;

-- =========================
-- SELECT (público)
-- =========================
create policy "Public read access"
on storage.objects
for select
using (bucket_id = 'imagens-cardapio');

-- Remove as políticas se já existirem para evitar o erro 42710
DROP POLICY IF EXISTS "Public read access" ON storage.objects;
DROP POLICY IF EXISTS "Anon insert access" ON storage.objects;
DROP POLICY IF EXISTS "Anon update access" ON storage.objects;
DROP POLICY IF EXISTS "Anon delete access" ON storage.objects;

-- Agora cria as políticas normalmente
create policy "Public read access" on storage.objects for select using (bucket_id = 'imagens-cardapio');
create policy "Anon insert access" on storage.objects for insert to anon, authenticated with check (bucket_id = 'imagens-cardapio');
create policy "Anon update access" on storage.objects for update to anon, authenticated using (bucket_id = 'imagens-cardapio');
create policy "Anon delete access" on storage.objects for delete to anon, authenticated using (bucket_id = 'imagens-cardapio');

-- 18
-- Cria a tabela snapshots, onde ficarao armazenados os dados do GA4
create table public.ga4_snapshots (
  id uuid not null default gen_random_uuid (),
  snapshot_date date not null,
  report_type text not null,
  data jsonb not null default '{}'::jsonb,
  created_at timestamp with time zone null default now(),
  constraint ga4_snapshots_pkey primary key (id),
  constraint ga4_snapshots_snapshot_date_report_type_key unique (snapshot_date, report_type)
) TABLESPACE pg_default;
-- Habilita RLS na tabela ga4_snapshots
alter table "public"."ga4_snapshots" enable row level security;
create policy "All Permissive"
on "public"."ga4_snapshots"
as PERMISSIVE
for ALL
to public
using (true)
with check (true);

-- 19
-- Cria tabela anti-pausa supabase
create table public.keep_alive (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  "check" timestamp with time zone null default (now() AT TIME ZONE 'utc'::text),
  constraint keep_alive_pkey primary key (id)
) TABLESPACE pg_default;
-- Habilita RLS na tabela configuracoes
alter table "public"."keep_alive" enable row level security;
create policy "All Permissive"
on "public"."keep_alive"
as PERMISSIVE
for ALL
to public
using (true)
with check (true);

-- 20
-- Cria a funcao RPC do update_cron
CREATE OR REPLACE FUNCTION public.execute_cron_update(
  cron_expression TEXT,
  function_url TEXT,
  anon_key TEXT
)
RETURNS void
LANGUAGE plpgsql
AS $$
BEGIN
  -- 1. Remove o job existente (ignora erro se não existir)
  BEGIN
    PERFORM cron.unschedule('ga4-daily-snapshot');
  EXCEPTION WHEN OTHERS THEN
    NULL;
  END;

-- Cria o novo job com a expressão cron fornecida
  PERFORM cron.schedule(
    'ga4-daily-snapshot',
    cron_expression,
    format(
      $job$
      SELECT net.http_post(
        url := %L,
        headers := %L::jsonb,
        body := '{"mode": "snapshot"}'::jsonb
      ) AS request_id;
      $job$,
      function_url,
      json_build_object(
        'Content-Type', 'application/json', 
        'Authorization', 'Bearer ' || anon_key
      )::text
    )
  );
END;
$$;

-- Funções para consultar LTV por campanha e por source:
CREATE OR REPLACE FUNCTION public.get_ltv_by_utm_source(start_date timestamp with time zone DEFAULT NULL, end_date timestamp with time zone DEFAULT NULL)
RETURNS TABLE(utm_source text, customer_count bigint, total_revenue numeric, avg_ltv numeric)
LANGUAGE sql STABLE AS $$
  WITH pedidos_filtrados AS (
    SELECT p.firebase_id, LOWER(p.user_email) AS user_email, p.valor_total
    FROM public.pedidos_sabor_delivery p
    WHERE COALESCE(p.valor_total, 0) > 0
      AND (p.status_atual IS NULL OR p.status_atual NOT IN ('cancelado','Cancelado','cancelled'))
      AND (start_date IS NULL OR p.criado_em >= start_date)
      AND (end_date IS NULL OR p.criado_em <= end_date)
  ),
  por_cliente AS (
    SELECT
      COALESCE(u.first_utm_source, '(direto)') AS utm_source,
      u.id AS customer_key,
      SUM(pf.valor_total) AS ltv
    FROM public.users u
    JOIN pedidos_filtrados pf
      ON (u.firebase_id IS NOT NULL AND u.firebase_id = pf.firebase_id)
      OR (u.email IS NOT NULL AND LOWER(u.email) = pf.user_email)
    GROUP BY 1, 2
  )
  SELECT utm_source, COUNT(*)::bigint, SUM(ltv)::numeric, ROUND(AVG(ltv)::numeric, 2)
  FROM por_cliente GROUP BY utm_source ORDER BY 4 DESC;
$$;

CREATE OR REPLACE FUNCTION public.get_ltv_by_utm_campaign(start_date timestamp with time zone DEFAULT NULL, end_date timestamp with time zone DEFAULT NULL)
RETURNS TABLE(utm_campaign text, customer_count bigint, total_revenue numeric, avg_ltv numeric)
LANGUAGE sql STABLE AS $$
  WITH pedidos_filtrados AS (
    SELECT p.firebase_id, LOWER(p.user_email) AS user_email, p.valor_total
    FROM public.pedidos_sabor_delivery p
    WHERE COALESCE(p.valor_total, 0) > 0
      AND (p.status_atual IS NULL OR p.status_atual NOT IN ('cancelado','Cancelado','cancelled'))
      AND (start_date IS NULL OR p.criado_em >= start_date)
      AND (end_date IS NULL OR p.criado_em <= end_date)
  ),
  por_cliente AS (
    SELECT
      COALESCE(u.first_utm_campaign, '(sem campanha)') AS utm_campaign,
      u.id AS customer_key,
      SUM(pf.valor_total) AS ltv
    FROM public.users u
    JOIN pedidos_filtrados pf
      ON (u.firebase_id IS NOT NULL AND u.firebase_id = pf.firebase_id)
      OR (u.email IS NOT NULL AND LOWER(u.email) = pf.user_email)
    GROUP BY 1, 2
  )
  SELECT utm_campaign, COUNT(*)::bigint, SUM(ltv)::numeric, ROUND(AVG(ltv)::numeric, 2)
  FROM por_cliente GROUP BY utm_campaign ORDER BY 4 DESC;
$$;

ALTER TABLE users
ADD COLUMN IF NOT EXISTS first_utm_source TEXT,
ADD COLUMN IF NOT EXISTS first_utm_campaign TEXT;


-- 12
-- Cria a função, o trigger e a tabela "customer_data" no schema public
CREATE OR REPLACE FUNCTION public.update_customer_data_updated_at ()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;
create table public.customer_data (
  id uuid not null default gen_random_uuid (),
  name text not null,
  phone text not null,
  cep text null,
  street text null,
  number text null,
  complement text null,
  neighborhood text null,
  city text null,
  state text null,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now(),
  constraint customer_data_pkey primary key (id),
  constraint customer_data_phone_key unique (phone)
) TABLESPACE pg_default;
create trigger update_customer_data_updated_at BEFORE
update on customer_data for EACH row
execute FUNCTION update_customer_data_updated_at ();
alter table "public"."customer_data" enable row level security;
create policy "Acesso público total temporário"
on "public"."customer_data"
as PERMISSIVE
for ALL
to public
using (true)
with check (true);

CREATE FUNCTION public.get_user_role(user_uid uuid)
RETURNS text -- Ou o tipo da sua coluna 'role', ex: user_role_enum
LANGUAGE sql
STABLE -- Indica que a função apenas lê dados, melhorando a performance
AS $$
  SELECT role FROM public.users 
  WHERE user_id = user_uid 
  LIMIT 1;
$$;
CREATE FUNCTION public.get_user_role(user_uid text)
RETURNS text
LANGUAGE sql
STABLE
AS $$
  SELECT role FROM public.users 
  WHERE firebase_id = user_uid 
  LIMIT 1;
$$;
